### ISSUE TITLE
Sending a Full Config File

### ISSUE THREAD

**Issue by kvedder-amplex** [IPInfusion/ocnos-ansible-collection#2]
Hello,

I am trying to send a config using Ansible 5.2.0 with :
```
---
- hosts: ocnos
  gather_facts: false

  tasks:

  - name: load a config from disk and replace the current config
    ipinfusion.ocnos.ocnos_config:
      src: hq-core-1.cfg
      backup: yes
      replace: line
    register: result

```
I get:
`OSError: [Errno 36] File name too long: 'hostname router01\n!\nnmp-server enable traps link linkDown\`

It appears to be trying to put the file contents into the file name field.

Can someone assist?
