### ISSUE TITLE
CLI warnings are treated as errors

### ISSUE THREAD

**Issue by fzakfeld** [IPInfusion/ocnos-ansible-collection#4]
When configuring breakouts, the CLI issues a warning. The ansible role treats this as an error and aborts the play, even though the configuration is valid and went successfully.

```
- name: Configure breakouts
  ipinfusion.ocnos.ocnos_config:
    lines:
      - port 8 breakout 4X25g
      - port 9 breakout 4X25g
```

Will result in:
```
"msg": "commit\r\r\n%% Warning : The interfaces & associated configs are deleted for this port/port-group \r\ncswitch_hostname(config)#"
```

A workaround is to use custom logic for failed_when and changed_when, but the ansible module should handle it correctly.
```
- name: Configure breakouts
  ipinfusion.ocnos.ocnos_config:
    lines:
      - port 8 breakout 4X25g
      - port 9 breakout 4X25g
  register: _result
  failed_when: _result.failed and 'msg' in _result and 'Warning' not in _result.msg
  changed_when: _result.changed or ('msg' in _result and 'Warning' in _result.msg)
```
